Implements osm::Lane and osm::Segment classes.
maliput/maliput_osm pull request #5
Opened 2022-09-22 20:07 UTC by francocipollone

# 🎉 New feature

Related to #1 

## Summary

Lane and Segment classes/strucutres to be filled by the parser(During OSMManager's constructor time) and to be provided by the OSMManager. For reference the OSMManager
```cpp
namespace maliput_osm {
namespace osm {

class OSMManager {
 public:
  MALIPUT_NO_COPY_NO_MOVE_NO_ASSIGN(OSMManager)

  OSMManager(const std::string& osm_file_path);

  ~OSMManager();

  const std::unordered_map<SegmentId, Segment>& GetOSMSegments() const;

 private:
  class Impl;
  std::unique_ptr<Impl> impl_;
};

}  // namespace osm
}  // namespace maliput_osm
```

## Test it

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-09-22 20:24 UTC, francocipollone commented
An alternative could be to not group the `Lanes` in `Segments` and from the `OSMManger` just provide a `GetLanes` to get all the lanes. Then the builder will be in charge of grouping the lanes into segments.

2022-09-23 17:20 UTC, agalbachicar commented
META: can we change Lane and Segment to be structs with just fields? I don't think it makes sense to add all the boilerplate code for data structs that have no logic at all. If we want to make them const , that can be done holding a const Lane& / const Segment& and we have a getter and a setter for each member so in the end we are adding x3 LOC without much purpose.

I would keep the operator== overload though.

2022-09-26 21:44 UTC, francocipollone commented
> META: can we change Lane and Segment to be structs with just fields? I don't think it makes sense to add all the boilerplate code for data structs that have no logic at all. If we want to make them const , that can be done holding a const Lane& / const Segment& and we have a getter and a setter for each member so in the end we are adding x3 LOC without much purpose.
> 
> I would keep the operator== overload though.

Done

2022-09-27 12:45 UTC, agalbachicar requested changes
Minor comments, it is looking good!

2022-09-27 12:45 UTC, agalbachicar commented on src/maliput_osm/osm/lane.h
> +using LaneId = std::string;
Nit: move it inside Lane and call it Id so we don't have any name collision when implementing the parser with maliput::api::LaneId.

2022-09-27 12:45 UTC, agalbachicar commented on src/maliput_osm/osm/lane.h
> +  std::vector<LaneId> successors;
Isn't it better to have a std::unordered_set here?

2022-09-27 12:45 UTC, agalbachicar commented on src/maliput_osm/osm/segment.h
> +using SegmentId = std::string;
Same comment as in lane.h.

2022-09-27 12:45 UTC, agalbachicar commented on src/maliput_osm/osm/segment.h
> + public:
Nit: you can remove it.

2022-09-27 12:45 UTC, agalbachicar commented on src/maliput_osm/osm/segment.h
> +  std::map<LaneId, Lane> lanes;
Consider using std::unordered_map

2022-09-27 12:45 UTC, agalbachicar commented on src/maliput_osm/osm/segment.h
> +  std::vector<SegmentId> successors;
Do we actually expect to parse this information? Is it useful?
Anyway, I would use std::unordered_set instead.

2022-09-27 12:45 UTC, agalbachicar commented on src/maliput_osm/osm/segment.h
> +/// A segment is a collection of lanes added with a strict order, from right to left,
Hmm, besides my comments about collections, lanes are stored in a map so the ordering is based on how lane IDs relate to each other. Shouldn't we use an index instead?

2022-09-27 12:45 UTC, agalbachicar commented on test/osm/CMakeLists.txt
> +add_dependencies_to_test(segment_test)
```suggestion

add_dependencies_to_test(lane_test)
add_dependencies_to_test(segment_test)
```

2022-09-27 12:45 UTC, agalbachicar commented on test/osm/CMakeLists.txt
> +add_dependencies_to_test(segment_test)
Just to have a clear group differentiation.

2022-09-27 12:45 UTC, agalbachicar commented on test/osm/lane_test.cc
> +  EXPECT_EQ(dut, dut2);
Let's make this test in another case.

2022-09-27 12:45 UTC, agalbachicar commented on test/osm/segment_test.cc
> +  EXPECT_EQ(dut, dut2);
Same comment as in the lane_test.

2022-09-27 12:47 UTC, francocipollone commented on src/maliput_osm/osm/segment.h
> +  std::map<LaneId, Lane> lanes;
Mind the ordering in segment.

2022-09-27 12:49 UTC, francocipollone commented on src/maliput_osm/osm/segment.h
> +  std::vector<SegmentId> successors;
We could remove it and add it if necessary later on when connections between lanes are supported

2022-09-27 12:49 UTC, francocipollone commented on src/maliput_osm/osm/segment.h
> +/// A segment is a collection of lanes added with a strict order, from right to left,
Ups, you're right

2022-09-27 14:16 UTC, francocipollone commented on test/osm/segment_test.cc
> +  EXPECT_EQ(dut, dut2);
Done.

2022-09-27 14:16 UTC, francocipollone commented on test/osm/lane_test.cc
> +  EXPECT_EQ(dut, dut2);
Done.

2022-09-27 14:17 UTC, francocipollone commented on src/maliput_osm/osm/segment.h
> +  std::map<LaneId, Lane> lanes;
Used a vector instead as order matters.

2022-09-27 14:18 UTC, francocipollone commented on src/maliput_osm/osm/segment.h
> + public:
Done.

2022-09-27 14:18 UTC, francocipollone commented on src/maliput_osm/osm/lane.h
> +  std::vector<LaneId> successors;
Done.

2022-09-27 14:18 UTC, francocipollone commented on src/maliput_osm/osm/lane.h
> +using LaneId = std::string;
Done.

2022-09-28 14:23 UTC, agalbachicar approved these changes
LGTM

2022-09-28 15:09 UTC, merged