WIP: Adds OSMManager
maliput/maliput_osm pull request #7
Opened 2022-09-27 16:05 UTC by francocipollone

# 🎉 New feature

Part of https://github.com/maliput/maliput_osm/issues/6

## Summary
Adds OSMManager

It relies on lanelet2's parser for parsing the lanelet2-osm map.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

2022-09-27 16:08 UTC, francocipollone commented on CMakeLists.txt
> +ament_environment_hooks("${CMAKE_CURRENT_SOURCE_DIR}/env-hooks/${PROJECT_NAME}.sh.in")
I'd like to use ` ament_index` here instead, for the resources management.

2022-09-29 16:17 UTC, francocipollone commented on src/test_utilities/osm_types_compare.h
> +                                               const maliput_sparse::geometry::LineString3d& rhs, double tolerance);
I will push this to maliput_sparse::test_utilities as probably it is something to be used by other backends.

2022-10-03 18:02 UTC, agalbachicar requested changes
Just a few comments.

2022-10-03 19:46 UTC, francocipollone commented on src/maliput_osm/osm/osm_manager.cc
> +    const Segment::Id segment_id{"segment_" + std::to_string(lanelet.id())};
Agree, however this method will change shortly. At the moment we are assigning only one lane per segment and here we are just adding a "segment_" as a prefix arbitrarly.

We should define how the assignment of ids for the segments will be. However this will be tackled in a follow up pr

2022-10-03 19:48 UTC, francocipollone commented on test/osm/conversions_test.cc
> +  const Lane::Id lane_id{"10"};
Done.

2022-10-03 19:49 UTC, francocipollone commented on test/osm/conversions_test.cc
> +}  // namespace maliput_osm
Done

2022-10-03 19:49 UTC, francocipollone commented on src/maliput_osm/osm/conversions.cc
> +
Done.

2022-10-03 19:58 UTC, francocipollone commented on src/maliput_osm/osm/osm_manager.cc
> +    const Segment::Id segment_id{"segment_" + std::to_string(lanelet.id())};
https://github.com/maliput/maliput_osm/issues/16#issuecomment-1265960039

2022-10-04 18:19 UTC, agalbachicar requested changes
I think you can merge the dependent PR and try once more with CI.

2022-10-05 12:51 UTC, francocipollone commented
> I think you can merge the dependent PR and try once more with CI.

Yep, CI passes now

2022-10-05 13:30 UTC, agalbachicar approved these changes
LGTM

2022-10-05 13:36 UTC, merged